/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonCardHeader: typeof import('@ionic/vue')['IonCardHeader']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonGrid: typeof import('@ionic/vue')['IonGrid']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonListHeader: typeof import('@ionic/vue')['IonListHeader']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonPopover: typeof import('@ionic/vue')['IonPopover']
    IonRadio: typeof import('@ionic/vue')['IonRadio']
    IonRadioGroup: typeof import('@ionic/vue')['IonRadioGroup']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonRow: typeof import('@ionic/vue')['IonRow']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonText: typeof import('@ionic/vue')['IonText']
    IonTextarea: typeof import('@ionic/vue')['IonTextarea']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    ItemExample: typeof import('./src/components/ItemExample.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
